GET https://7rphtky6f1.execute-api.ap-northeast-1.amazonaws.com/dev/food/foodid=aaa?food=ramen&drink=cola
// ヘッダー名: ヘッダーの名前
Authorization: GHI

{
"message":"JKL"
}

// パスパラメーター: id(日付、ユーザーID)等の何かを識別するもの
// クエリストリング: getパラメータ(検索条件など)
// リクエストボディ: なんでもオッケー（メインの内容）基本POSTで使われる
//                  GETで使うことも可能だが上記2件と内容が被る
//                  ※メリット内容が暗号化されるためユーザーは見えない
// リクエストヘッダ: 自由にヘッダーをつけれるものじゃない
//                  →誰がつけるの？　世界
//                  送信すり内容によって使用有無すら異なるのでやりたい事と都度すり合わせる